### ISSUE TITLE
確率密度関数グラフのTarget Probabilityの意味

### ISSUE THREAD

**Issue by akinkmr** [FujitsuLaboratories/COMEVIZZ#11]
Target プロジェクトが一つだと、Target Probabilityのスケールが0を中央にマイナスも表示されるのですが、確率(Probability)に負の数は無いので、一体どういう意味になるのでしょうか?

**Comment by ysknmt** [comment]
`Target Probability`の軸は赤いポイントに対する軸であり、値自体がマイナスとなっている訳ではありません。0を表しています。
![image](https://user-images.githubusercontent.com/32432897/34199643-c7c48798-e5b1-11e7-977b-37b33fc869d7.png)

ただ、`Target Probability`の値が0であること自体がエラーのようです。
これはtargetデータが一つの場合に`sd`関数による標準偏差の計算が正しく行われないことが原因となっているようです。すぐに修正します。

また、軸としてマイナスの値も表示されてしまっていると混乱を引き起こしてしまうため、軸の表示についても併せて見直します。

**Comment by ysknmt** [comment]
もし、まだ問題が発生するようならばreopenしてください。
