### ISSUE TITLE
「Normalized by lines」と複雑度についての質問

### ISSUE THREAD

**Issue by ATFU** [FujitsuLaboratories/COMEVIZZ#13]
不明点が２点ほどありますので、質問させて下さい。

(1) 「Normalized by lines」の機能ですが、どのような場面で有効にすべきかをご教授お願いできませんでしょうか。
    例えば、標準で用意されているSelect Metrics Setsの場合、以下の内容を想定していますが、機能的に間違いはありませんでしょうか。
      - Issues    : 有効
      - Violations: 有効
      - Complexity: 無効
(2) 以下のメトリクスの違いを教えて頂けませんでしょうか。
      - function_complexity と complexity_in_functions
      - class_complexity と complexity_in_class

よろしくお願い致します。

**Comment by ysknmt** [comment]
ご質問ありがとうございます。

> (1) 「Normalized by lines」の機能ですが、どのような場面で有効にすべきかをご教授お願いできませんでしょうか。

Code SmellsやViolationsのような、コード量が多いほど値(指摘数)が増加するようなメトリクスについて`Normalized by lines`によって正規化を行うことを想定しています。
ですので、デフォルトのメトリクスセット(Issues, Violations, Complexity)については、おっしゃる通りの使い分けになるかと思います。

ただ、Complexityセットのcomplexityメトリクスについては少々上記の説明と異なる部分があるかと思います。
現在のデフォルトセットに含まれているメトリクス群は、あるチームのヒアリング内容から決定したメトリクス群を我々の方で各セットに分けたものであるため、少々齟齬が発生しております。

> (2) 以下のメトリクスの違いを教えて頂けませんでしょうか。

[Metric Definitions \- SonarQube 6\.2 \- Doc SonarQube](https://docs.sonarqube.org/display/SONARQUBE62/Metric+Definitions)
> function_complexity - Average complexity by function.

`function_complexity`については上記の通り、１関数内に含まれるcomplexityの平均値を表しており、`complexity_in_function`については、下記のQAの説明のとおり解釈しています。

[SonarQube Users \(archive\) \- Question about JavaScript complexity/function](http://sonarqube-archive.15.x6.nabble.com/Question-about-JavaScript-complexity-function-td5034077.html)
> Moreover, the complexity/function is calculated as the following: 
> (COMPLEXITY_IN_FUNCTION / NUMBER_OF_FUNCTION) where COMPLEXITY_IN_FUNCTION = OUTER_COMPLEXITY + INNER_COMPLEXITY.
> So we end with 3 / 2 = 1.5 complexity/function.

つまり、`complexity_in_function = function_complexity * functions` という式が成り立つものと解釈しています。
実際に計算すると値が少々異なりますが、`function_complexity`の有効桁数によるものだと考えています。

※メトリクスの解釈についてはSonarSource社の公式見解でないことにご留意ください

---

ということを書いていて、デフォルトセット・Complexityのメトリクスを`complexity`, `complexity_in_function`, `complexity_in_class`にすると、全て`Normalized by lines`の対象とできますね・・そちらの方が良いかもしれません。ありがとうございます。

**Comment by ATFU** [comment]
以下の２点の違いについて教えて頂きありがとうございます。
  - function_complexity と complexity_in_functions
  - class_complexity と complexity_in_class

Metric Definitions のページについては、こちら側も把握しておりましたが、complexity_in_functions及びcomplexity_in_classが見つからなかった為、困っておりました。

>デフォルトセット・Complexityのメトリクスをcomplexity, complexity_in_function, complexity_in_classにすると、
>全てNormalized by linesの対象とできますね・・そちらの方が良いかもしれません。ありがとうございます。
デフォルトセットについてもアドバイスを頂きありがとうございます。
追加で確認させてください。
3点のメトリクスキーですが、3点ともプロジェクト全体の複雑度に読み取れましたが、どのように違うのでしょうか。
メトリクスキーの値やZ-Scoreで出力したグラフが異なる内容なので、それぞれ異なる内容と捕えているのですが、意味が分かっておらず、教えて頂けると大変助かります。

以上、よろしくお願い致します。

**Comment by ysknmt** [comment]
> 3点のメトリクスキーですが、3点ともプロジェクト全体の複雑度に読み取れましたが、どのように違うのでしょうか。

`complexity`: プロジェクト全体の複雑度合計
`complexity_in_class`: 全てのJavaクラス内の複雑度合計
`complexity_in_functions`: 全ての関数内の複雑度合計

関係性としては、下記のようになるかと思います。

`complexity = complexity_in_classes > complexity_in_functions`

Javaの場合、`complexity_in_functions`のみが static初期化子や匿名クラス内で発生した複雑度をカウントしないため、他の複雑度指標値よりも値が小さくなります。
`complexity`と`complexity_in_classes`はJavaの場合は同じ値になるメトリクスだと考えられるため、同時に表示する意味は無いようですね...。

> メトリクスキーの値やZ-Scoreで出力したグラフが異なる内容なので、それぞれ異なる内容と捕えているのですが、意味が分かっておらず、教えて頂けると大変助かります。

ただ、現在[公開しているデータ](https://github.com/FujitsuLaboratories/COMEVIZZ/blob/master/data/gitminer_sonar_all_data_2017_04_25.csv)にてメトリクス値の内容を精査したところ、上記の説明と整合性が合わない部分があることが分かりました。(例: complexity_in_functionsがcomplexity_in_classよりも大きい)
公開データについても見直しを行っていきたいと思います。申し訳ございません。

ご質問によって内容の精査を行う機会ができており、大変助かっております。
ありがとうございます。

**Comment by ysknmt** [comment]
Issueクローズいたします。
追加の確認事項がある場合はreopenするか新しいIssueを立ててください。
