### ISSUE TITLE
チャート画像のダウンロードについてのリクエスト

### ISSUE THREAD

**Issue by warama17** [FujitsuLaboratories/COMEVIZZ#21]
複数のプロジェクト間のコード品質を客観的に比較できるので、とても重宝しています。  
その際にチャート画像を右クリックで保存しているのですが、複数回繰り返すのが若干煩わしく感じています。  

リクエスト：  
* 表示される画像をダウンロードして適切な名前で保存してくれる機能の追加    

ご検討いただけるとありがたいです。

**Comment by ysknmt** [comment]
下記のような画像ダウンロード用のダイアログを追加しました。
`適切な名前`というものが難しいため日時を含むファイル名をデフォルト名として入力し、自由に変更できるようにしてあります。

![2018-04-26 14 13 25](https://user-images.githubusercontent.com/32432897/39286981-0cf0d69c-495c-11e8-9d8a-3df8671f2816.png)

**Comment by warama17** [comment]
早々にご対応いただき、ありがとうございます。  
正に、欲しかった機能です。今後も使わせていただきます!
